### ISSUE TITLE
Initial Release TODO

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/website#1]
Here is a list of items that need to be completed before we can release the site:
- [ ] Setup travis-ci with cobalt and github pages
- [ ] Style the site
- [ ] Create example pages
    - [ ] Basic example of a cobalt site.
    - [ ] Basic blogging website
    - [ ] More complicated blogging site with use of tags

Feel free to let me know if I missed something.

**Comment by rjgoldsborough** [comment]
Howdy.

I'd like to help work on the TODO and get the site set up.

I can definitely start doing the first two.
I could submit a PR with an appropriate .travis.yml file. I know some token stuff will be needed though.

Do y'all have a design in mind for the styling?

**Comment by rjgoldsborough** [comment]
So I took a couple hours and looked at some other static site generators to get an idea and then threw together a little prototype here:

https://rjgoldsborough.github.io/cobalt-website/

It should be pretty mobile friendly and has only one breakpoint.

Again, not too sure of the plan but lemme know what y'all think, even if it's to say it stinks or
you already have a design and I should stop. :)

**Comment by LucioFranco** [comment]
@rjgoldsborough love it! I'm not a design person but I think it looks good. If you want to get it to a state that you are ready for it to be published just make a PR! Thanks for the contribution. Ping me on gitter if you have any questions.

**Comment by johannhof** [comment]
Yay, that's pretty awesome already. As @LucioFranco mentioned said, if you make a PR I think we could merge this right now and improve on it gradually. We should make an SVG out of the icon and some CSS dimensions/alignments might need another px or two.

👍 👍 👍

**Comment by rjgoldsborough** [comment]
Sweet! I'll keep working on this then. \o/

Yeah, svg++. I was thinking about trying to HTML/CSSize it but I think it'd be more trouble than it's worth. I was going to ask if anyone had an illustrator file or fonts for the logo because it'd really crisp it up. It looks slightly blurry on a mobile phone.

I saw some talk/issues about sass and it kind of sounds like it works but just isn't merged?
Is that right? If not, no biggie but sass does make things much nicer.

What're y'alls thoughts on browser support?
I'm using a few css3 things that IE11 doesn't support and will probably need to prefix/polyfill/etc.

**Comment by johannhof** [comment]
> I was going to ask if anyone had an illustrator file or fonts for the logo because it'd really crisp it up.

https://github.com/cobalt-org/logos/blob/master/cobald.logo.02.ai is the file you're looking for as far as I can tell :)

> I saw some talk/issues about sass and it kind of sounds like it works but just isn't merged?

Sass/preprocessor support is a thing I'd like to focus on soon, yes. But we're not 100% there yet.

>  I'm using a few css3 things that IE11 doesn't support and will probably need to prefix/polyfill/etc.

If it takes you more than a few minutes to add IE11 support I'm pretty sure it's not worth your time. Maybe we should make sure the site doesn't look horribly broken on IE, but apart from that I really don't care.

Thanks!!!

**Comment by rjgoldsborough** [comment]
Ah, yup, that's the file. Thanks.

**Comment by rjgoldsborough** [comment]
Is that font located somewhere I'm not looking? I don't have it so cannot save out the full logo from Illustrator.

**Comment by rjgoldsborough** [comment]
https://rjgoldsborough.github.io/cobalt-website/

I made a few updates.

I tried out and kind of like the grey section. This may not look as good and be easy to read on a longer docs like page but I don't think it looks bad here.

Also, I added the logo as an svg. Like I said above, I don't have that font so Illustrator just tries to substitute it for one I do have.

Lemme know what y'all think of the grey and if I can find that font somewhere.

I think my next course of action is getting this built with cobalt and then making the readme into a more doc like page.

**Comment by LucioFranco** [comment]
@rjgoldsborough looking good. I would maybe change the BG to another color besides grey. And I would also have the github link point to the cobalt.rs repo not the github org.

**Comment by rjgoldsborough** [comment]
pushed an update that tries a blue bg

**Comment by johannhof** [comment]
Don't want to bikeshed, just saying I liked it better before the blue :)

**Comment by johannhof** [comment]
> Is that font located somewhere I'm not looking? I don't have it so cannot save out the full logo from Illustrator.

I'm not particularly attached to the font anyway, we could just make a new logo font using a more common type.

**Comment by rjgoldsborough** [comment]
Nah, I appreciate the honest feedback :)
I'm really just throwing up ideas and trying to break up the white a bit.
But I also don't think the all white looks terrible.

Cool. I will tinker around with some and see what I can come up with.

**Comment by pickfire** [comment]
If build fails, https://github.com/travis-ci/travis-ci/issues/9312#issuecomment-371590249

**Comment by epage** [comment]
Ah, was wondering why my personal site was suddenly failing.  Made me have to dog food `cobalt import` (https://github.com/cobalt-org/cobalt.rs/issues/394) :)
